<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <CentralPackageTransitivePinningEnabled>false</CentralPackageTransitivePinningEnabled>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="AutoMapper" Version="15.1.0" />
    <PackageVersion Include="BuildBundlerMinifier2022" Version="2.9.11" />
    <PackageVersion Include="BuildWebCompiler2022" Version="1.14.15" />
    <PackageVersion Include="ClosedXML" Version="0.105.0" />
    <PackageVersion Include="DocumentFormat.OpenXml" Version="3.3.0" />
    <PackageVersion Include="EFCore.BulkExtensions" Version="9.0.2" />
    <PackageVersion Include="Markdig" Version="0.43.0" />
    <PackageVersion Include="MediatR" Version="13.1.0" />
    <PackageVersion Include="Microsoft.Agents.AI" Version="1.18.0" />
    <PackageVersion Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="9.0.10" />
    <PackageVersion Include="Microsoft.AspNetCore.Components" Version="9.0.18" />
    <PackageVersion Include="Microsoft.AspNetCore.Components.Authorization" Version="9.0.18" />
    <PackageVersion Include="Microsoft.AspNetCore.Components.DataAnnotations.Validation" Version="3.2.0-rc1.20223.4" />
    <PackageVersion Include="Microsoft.AspNetCore.Components.Web" Version="9.0.18" />
    <PackageVersion Include="Microsoft.AspNetCore.Components.WebAssembly.Server" Version="9.0.18" />
    <PackageVersion Include="Microsoft.AspNetCore.Http.Abstractions" Version="2.3.0" />
    <PackageVersion Include="Microsoft.AspNetCore.Identity.UI" Version="$(AspNetCoreVersion)" />
    <PackageVersion Include="Microsoft.AspNetCore.Mvc.Core" Version="2.3.0" />
    <PackageVersion Include="Microsoft.AspNetCore.Mvc.Versioning" Version="5.1.0" />
    <PackageVersion Include="Microsoft.AspNetCore.OpenApi" Version="$(AspNetCoreVersion)" />
    <PackageVersion Include="Microsoft.AspNetCore.SignalR.Client" Version="$(AspNetCoreVersion)" />
    <PackageVersion Include="Microsoft.CodeAnalysis.CSharp" Version="4.14.0" />
    <PackageVersion Include="Microsoft.CodeAnalysis.CSharp.Workspaces" Version="4.14.0" />
    <PackageVersion Include="Microsoft.CodeAnalysis.Common" Version="4.14.0" />
    <PackageVersion Include="Microsoft.CodeAnalysis.VisualBasic" Version="4.14.0" />
    <PackageVersion Include="Microsoft.CodeAnalysis.VisualBasic.Workspaces" Version="4.14.0" />
    <PackageVersion Include="Microsoft.CodeAnalysis.Workspaces.Common" Version="4.14.0" />
    <PackageVersion Include="Microsoft.Data.Sqlite" Version="9.0.10" />
    <PackageVersion Include="Microsoft.EntityFrameworkCore" Version="$(AspNetCoreVersion)" />
    <PackageVersion Include="Microsoft.EntityFrameworkCore.Design" Version="$(AspNetCoreVersion)" />
    <PackageVersion Include="Microsoft.EntityFrameworkCore.Relational" Version="$(AspNetCoreVersion)" />
    <PackageVersion Include="Microsoft.EntityFrameworkCore.Sqlite" Version="$(AspNetCoreVersion)" />
    <PackageVersion Include="Microsoft.EntityFrameworkCore.SqlServer" Version="9.0.2" />
    <PackageVersion Include="Microsoft.EntityFrameworkCore.Tools" Version="$(AspNetCoreVersion)" />
    <PackageVersion Include="Microsoft.Extensions.AI.OpenAI" Version="10.9.0" />
    <PackageVersion Include="Microsoft.Extensions.AI" Version="10.9.0" />
    <PackageVersion Include="Microsoft.Extensions.Caching.Abstractions" Version="$(AspNetCoreVersion)" />
    <PackageVersion Include="Microsoft.Extensions.Configuration.Abstractions" Version="$(AspNetCoreVersion)" />
    <PackageVersion Include="Microsoft.Extensions.Configuration.Binder" Version="9.0.18" />
    <PackageVersion Include="Microsoft.Extensions.DependencyInjection" Version="$(AspNetCoreVersion)" />
    <PackageVersion Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="$(AspNetCoreVersion)" />
    <PackageVersion Include="Microsoft.Extensions.Hosting" Version="$(AspNetCoreVersion)" />
    <PackageVersion Include="Microsoft.Extensions.Hosting.WindowsServices" Version="$(AspNetCoreVersion)" />
    <PackageVersion Include="Microsoft.Extensions.Http" Version="$(AspNetCoreVersion)" />
    <PackageVersion Include="Microsoft.Extensions.Identity.Core" Version="$(AspNetCoreVersion)" />
    <PackageVersion Include="Microsoft.Extensions.Identity.Stores" Version="$(AspNetCoreVersion)" />
    <PackageVersion Include="Microsoft.Extensions.Logging" Version="$(AspNetCoreVersion)" />
    <PackageVersion Include="Microsoft.Extensions.Logging.Abstractions" Version="$(AspNetCoreVersion)" />
    <PackageVersion Include="Microsoft.FeatureManagement.AspNetCore" Version="4.4.0" />
    <PackageVersion Include="Microsoft.IdentityModel.Tokens" Version="8.14.0" />
    <PackageVersion Include="Microsoft.JSInterop" Version="$(AspNetCoreVersion)" />
    <PackageVersion Include="Microsoft.ML" Version="5.0.0" />
    <PackageVersion Include="Microsoft.ML.FastTree" Version="5.0.0" />
    <PackageVersion Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="9.0.0" />
    <PackageVersion Include="morelinq" Version="4.4.0" />
    <PackageVersion Include="Newtonsoft.Json" Version="13.0.4" />
    <PackageVersion Include="OpenAI" Version="2.13.0" />
    <PackageVersion Include="Serilog" Version="4.3.0" />
    <PackageVersion Include="Serilog.AspNetCore" Version="9.0.0" />
    <PackageVersion Include="Serilog.Extensions.Hosting" Version="9.0.0" />
    <PackageVersion Include="Serilog.Extensions.Logging" Version="9.0.2" />
    <PackageVersion Include="Serilog.Sinks.Console" Version="6.0.0" />
    <PackageVersion Include="Serilog.Sinks.Debug" Version="3.0.0" />
    <PackageVersion Include="Serilog.Sinks.File" Version="7.0.0" />
    <PackageVersion Include="Serilog.Sinks.Seq" Version="9.0.0" />
    <!--<PackageVersion Include="Stimulsoft.Reports.Blazor" Version="2023.1.1" />-->
    <PackageVersion Include="Solutaris.InfoWARE.ProtectedBrowserStorage" Version="1.0.2" />
    <PackageVersion Include="Swashbuckle.AspNetCore" Version="9.0.6" />
    <PackageVersion Include="Swashbuckle.AspNetCore.Annotations" Version="9.0.6" />
    <PackageVersion Include="System.Data.SqlClient" Version="4.9.0" />
    <PackageVersion Include="System.Data.SQLite.Core" Version="1.0.119" />
    <PackageVersion Include="System.Drawing.Common" Version="$(AspNetCoreVersion)" />
    <PackageVersion Include="System.IdentityModel.Tokens.Jwt" Version="8.14.0" />
    <PackageVersion Include="System.IO.Ports" Version="$(AspNetCoreVersion)" />
    <PackageVersion Include="System.Management" Version="$(AspNetCoreVersion)" />
    <PackageVersion Include="System.Text.Json" Version="10.0.3" />
    <PackageVersion Include="Telerik.UI.for.Blazor" Version="9.0.0" />
  </ItemGroup>
</Project>