// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SiloAI.Domains;

#nullable disable

namespace SiloAI.Domains.Migrations
{
    [DbContext(typeof(AiApiContext))]
    [Migration("20260923090311_AddFinancialLedger")]
    partial class AddFinancialLedger
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SiloAI.Domains.AiAdminUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("fld_Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("fld_CreatedAt");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("fld_IsActive");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("fld_Name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("fld_PasswordHash");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("fld_Username");

                    b.HasKey("Id");

                    b.ToTable("tbl_AiAdminUsers");
                });

            modelBuilder.Entity("SiloAI.Domains.AiApiKey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("fld_Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("fld_CreatedAt");

                    b.Property<int?>("CustomerId")
                        .HasColumnType("int")
                        .HasColumnName("fld_CustomerId");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("fld_ExpiresAt");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("bit")
                        .HasColumnName("fld_IsRevoked");

                    b.Property<string>("KeyValue")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("fld_KeyValue");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("fld_Label");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("tbl_AiApiKeys");
                });

            modelBuilder.Entity("SiloAI.Domains.AiChatSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("fld_Id");

                    b.Property<string>("ChatType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("fld_ChatType");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("fld_CreatedAt");

                    b.Property<string>("OwnerKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("fld_OwnerKey");

                    b.Property<string>("SessionState")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("fld_SessionState");

                    b.Property<int>("TurnIndex")
                        .HasColumnType("int")
                        .HasColumnName("fld_TurnIndex");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("fld_UpdatedAt");

                    b.HasKey("Id");

                    b.HasIndex("OwnerKey")
                        .HasDatabaseName("IX_tbl_AiChatSessions_fld_OwnerKey");

                    b.ToTable("tbl_AiChatSessions");
                });

            modelBuilder.Entity("SiloAI.Domains.AiConversation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("fld_Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BotAnswer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("fld_BotAnswer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("fld_CreatedAt");

                    b.Property<long?>("CreditUsage")
                        .HasColumnType("bigint")
                        .HasColumnName("fld_CreditUsage");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int")
                        .HasColumnName("fld_CustomerId");

                    b.Property<int?>("InstructionKey")
                        .HasMaxLength(500)
                        .HasColumnType("int")
                        .HasColumnName("fld_InstructionKey");

                    b.Property<int>("LocalConversationId")
                        .HasColumnType("int")
                        .HasColumnName("fld_LocalConversationId");

                    b.Property<string>("UserAsk")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("fld_UserAsk");

                    b.HasKey("Id");

                    b.ToTable("tbl_AiConversations");
                });

            modelBuilder.Entity("SiloAI.Domains.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("fld_Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("fld_CreatedAt");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("fld_Name");

                    b.Property<decimal>("RemainingCredit")
                        .HasColumnType("decimal(18,8)")
                        .HasColumnName("fld_RemainingCredit");

                    b.HasKey("Id");

                    b.ToTable("tbl_AiCustomers");
                });

            modelBuilder.Entity("SiloAI.Domains.FxRateSetting", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("fld_Id");

                    b.Property<DateTime>("EffectiveFrom")
                        .HasColumnType("datetime2")
                        .HasColumnName("fld_EffectiveFrom");

                    b.Property<decimal>("TomanPerUsd")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("fld_TomanPerUsd");

                    b.HasKey("Id");

                    b.HasIndex("EffectiveFrom")
                        .HasDatabaseName("IX_tbl_FxRateSettings_fld_EffectiveFrom");

                    b.ToTable("tbl_FxRateSettings");
                });

            modelBuilder.Entity("SiloAI.Domains.LedgerAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("fld_Id");

                    b.Property<decimal>("BalanceToman")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("fld_BalanceToman");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("fld_CreatedAt");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int")
                        .HasColumnName("fld_CustomerId");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasColumnName("fld_RowVersion");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("fld_UpdatedAt");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId")
                        .IsUnique()
                        .HasDatabaseName("IX_tbl_LedgerAccounts_fld_CustomerId");

                    b.ToTable("tbl_LedgerAccounts");
                });

            modelBuilder.Entity("SiloAI.Domains.LedgerTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("fld_Id");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("fld_AccountId");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("fld_Amount");

                    b.Property<decimal>("BalanceAfter")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("fld_BalanceAfter");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("fld_CreatedAt");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("fld_Description");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("fld_IdempotencyKey");

                    b.Property<int>("Type")
                        .HasColumnType("int")
                        .HasColumnName("fld_Type");

                    b.Property<Guid?>("UsageRecordId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("fld_UsageRecordId");

                    b.HasKey("Id");

                    b.HasIndex("AccountId")
                        .HasDatabaseName("IX_tbl_LedgerTransactions_fld_AccountId");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_tbl_LedgerTransactions_fld_CreatedAt");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("UX_tbl_LedgerTransactions_fld_IdempotencyKey");

                    b.HasIndex("UsageRecordId");

                    b.ToTable("tbl_LedgerTransactions");
                });

            modelBuilder.Entity("SiloAI.Domains.PricingSetting", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("fld_Id");

                    b.Property<DateTime>("EffectiveFrom")
                        .HasColumnType("datetime2")
                        .HasColumnName("fld_EffectiveFrom");

                    b.Property<int>("Feature")
                        .HasColumnType("int")
                        .HasColumnName("fld_Feature");

                    b.Property<decimal>("FloorToman")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("fld_FloorToman");

                    b.Property<decimal>("FloorUsd")
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("fld_FloorUsd");

                    b.Property<decimal>("Multiplier")
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("fld_Multiplier");

                    b.HasKey("Id");

                    b.HasIndex("Feature", "EffectiveFrom")
                        .HasDatabaseName("IX_tbl_PricingSettings_fld_Feature_fld_EffectiveFrom");

                    b.ToTable("tbl_PricingSettings");
                });

            modelBuilder.Entity("SiloAI.Domains.RagDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("fld_Id");

                    b.Property<string>("Category")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("fld_Category");

                    b.Property<int>("ChunkCount")
                        .HasColumnType("int")
                        .HasColumnName("fld_ChunkCount");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("fld_ContentType");

                    b.Property<DateTime>("CreateDateTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("fld_CreateDateTime");

                    b.Property<string>("CreatorUserId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("fld_CreatorUserId");

                    b.Property<string>("DocType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("fld_DocType");

                    b.Property<string>("FileHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasColumnName("fld_FileHash");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("nvarchar(260)")
                        .HasColumnName("fld_FileName");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint")
                        .HasColumnName("fld_FileSize");

                    b.Property<string>("Key")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("fld_Key");

                    b.Property<DateTime?>("LastUpdateDateTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("fld_LastUpdateDateTime");

                    b.Property<string>("LastUpdateUserId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("fld_LastUpdateUserId");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("nvarchar(260)")
                        .HasColumnName("fld_OriginalFileName");

                    b.Property<string>("ProcessingError")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)")
                        .HasColumnName("fld_ProcessingError");

                    b.Property<string>("ProcessingStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("fld_ProcessingStatus");

                    b.Property<string>("Tags")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("fld_Tags");

                    b.HasKey("Id");

                    b.HasIndex("Category")
                        .HasDatabaseName("IX_tbl_RagDocuments_fld_Category");

                    b.HasIndex("DocType")
                        .HasDatabaseName("IX_tbl_RagDocuments_fld_DocType");

                    b.HasIndex("FileHash")
                        .HasDatabaseName("IX_tbl_RagDocuments_fld_FileHash");

                    b.ToTable("tbl_RagDocuments");
                });

            modelBuilder.Entity("SiloAI.Domains.RagDocumentChunk", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("fld_Id");

                    b.Property<int>("ChunkIndex")
                        .HasColumnType("int")
                        .HasColumnName("fld_ChunkIndex");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("fld_Content");

                    b.Property<DateTime>("CreateDateTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("fld_CreateDateTime");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("fld_DocumentId");

                    b.Property<int>("TokenCount")
                        .HasColumnType("int")
                        .HasColumnName("fld_TokenCount");

                    b.HasKey("Id");

                    b.HasIndex("ChunkIndex")
                        .HasDatabaseName("IX_tbl_RagDocumentChunks_fld_ChunkIndex");

                    b.HasIndex("DocumentId")
                        .HasDatabaseName("IX_tbl_RagDocumentChunks_fld_DocumentId");

                    b.ToTable("tbl_RagDocumentChunks");
                });

            modelBuilder.Entity("SiloAI.Domains.RagInstruction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("fld_Id");

                    b.Property<string>("Category")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("fld_Category");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("fld_Content");

                    b.Property<DateTime>("CreateDateTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("fld_CreateDateTime");

                    b.Property<string>("CreatorUserId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("fld_CreatorUserId");

                    b.Property<int>("DocType")
                        .HasMaxLength(50)
                        .HasColumnType("int")
                        .HasColumnName("fld_DocType");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("fld_IsActive");

                    b.Property<bool>("IsSystematic")
                        .HasColumnType("bit")
                        .HasColumnName("fld_IsSystematic");

                    b.Property<string>("Key")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("fld_Key");

                    b.Property<DateTime?>("LastUpdateDateTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("fld_LastUpdateDateTime");

                    b.Property<string>("LastUpdateUserId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("fld_LastUpdateUserId");

                    b.Property<string>("Tags")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("fld_Tags");

                    b.HasKey("Id");

                    b.HasIndex("Category")
                        .HasDatabaseName("IX_tbl_RagInstructions_fld_Category");

                    b.HasIndex("DocType")
                        .HasDatabaseName("IX_tbl_RagInstructions_fld_DocType");

                    b.ToTable("tbl_RagInstructions");
                });

            modelBuilder.Entity("SiloAI.Domains.UsageRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("fld_Id");

                    b.Property<int>("CachedTokens")
                        .HasColumnType("int")
                        .HasColumnName("fld_CachedTokens");

                    b.Property<decimal>("ChargeToman")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("fld_ChargeToman");

                    b.Property<Guid?>("ConversationId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("fld_ConversationId");

                    b.Property<decimal>("CostUsd")
                        .HasColumnType("decimal(18,8)")
                        .HasColumnName("fld_CostUsd");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("fld_CreatedAt");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int")
                        .HasColumnName("fld_CustomerId");

                    b.Property<int>("Feature")
                        .HasColumnType("int")
                        .HasColumnName("fld_Feature");

                    b.Property<decimal>("FloorTomanUsed")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("fld_FloorTomanUsed");

                    b.Property<decimal>("FxRateUsed")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("fld_FxRateUsed");

                    b.Property<int>("InputTokens")
                        .HasColumnType("int")
                        .HasColumnName("fld_InputTokens");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("fld_Model");

                    b.Property<decimal>("MultiplierUsed")
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("fld_MultiplierUsed");

                    b.Property<int>("OutputTokens")
                        .HasColumnType("int")
                        .HasColumnName("fld_OutputTokens");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_tbl_UsageRecords_fld_CreatedAt");

                    b.HasIndex("CustomerId")
                        .HasDatabaseName("IX_tbl_UsageRecords_fld_CustomerId");

                    b.ToTable("tbl_UsageRecords");
                });

            modelBuilder.Entity("SiloAI.Domains.AiApiKey", b =>
                {
                    b.HasOne("SiloAI.Domains.Customer", "Customer")
                        .WithMany("AiApiKeys")
                        .HasForeignKey("CustomerId");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("SiloAI.Domains.LedgerAccount", b =>
                {
                    b.HasOne("SiloAI.Domains.Customer", "Customer")
                        .WithOne("LedgerAccount")
                        .HasForeignKey("SiloAI.Domains.LedgerAccount", "CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("SiloAI.Domains.LedgerTransaction", b =>
                {
                    b.HasOne("SiloAI.Domains.LedgerAccount", "Account")
                        .WithMany("Transactions")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SiloAI.Domains.UsageRecord", "UsageRecord")
                        .WithMany()
                        .HasForeignKey("UsageRecordId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Account");

                    b.Navigation("UsageRecord");
                });

            modelBuilder.Entity("SiloAI.Domains.RagDocumentChunk", b =>
                {
                    b.HasOne("SiloAI.Domains.RagDocument", "Document")
                        .WithMany("Chunks")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Document");
                });

            modelBuilder.Entity("SiloAI.Domains.UsageRecord", b =>
                {
                    b.HasOne("SiloAI.Domains.Customer", "Customer")
                        .WithMany("UsageRecords")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("SiloAI.Domains.Customer", b =>
                {
                    b.Navigation("AiApiKeys");

                    b.Navigation("LedgerAccount");

                    b.Navigation("UsageRecords");
                });

            modelBuilder.Entity("SiloAI.Domains.LedgerAccount", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("SiloAI.Domains.RagDocument", b =>
                {
                    b.Navigation("Chunks");
                });
#pragma warning restore 612, 618
        }
    }
}
