<Project Sdk="Microsoft.NET.Sdk">

    <ItemGroup>
        <PackageReference Include="Microsoft.Extensions.Configuration.Binder" />
        <PackageReference Include="OpenAI" />
        <PackageReference Include="Microsoft.Extensions.AI.OpenAI" />
        <PackageReference Include="Microsoft.Extensions.AI" />
        <PackageReference Include="Microsoft.Agents.AI" />
        <PackageReference Include="Microsoft.Extensions.VectorData.Abstractions" />
        <PackageReference Include="CommunityToolkit.VectorData.SqlServer" />
        <PackageReference Include="Markdig" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\SiloAI.Application.Shared\SiloAI.Application.Shared.csproj" />
      <ProjectReference Include="..\SiloAI.Domains\SiloAI.Domains.csproj" />
      <ProjectReference Include="..\SiloAI.Shared\SiloAI.Shared.csproj" />
	</ItemGroup>

</Project>
